Incorporate exchange rates in StableSwap operations
saber-hq/stable-swap pull request #144
Opened 2022-03-09 07:47 UTC by 0xIsshiki

The business logic changes can be verified by comparing any code in the [Curve contract](https://github.com/curvefi/curve-contract/blob/master/contracts/pools/y/StableSwapY.vy) that uses `_stored_rates()` with the code here in `price.rs` and `curve.rs`. All the other changes are test changes or passing stuff around.

This PR only changes existing tests but doesn't add any new specific tests. Will need to do that, but I thought it was worth getting this PR out in this state.

______
This PR was tested by running unit tests, e2e tests, and fuzz tests for a few minutes.

2022-03-09 17:01 UTC, michaelhly commented
Would you mind merging in the latest master so the CI workflows can run? 🙏

2022-03-13 00:49 UTC, michaelhly commented on stable-swap-client/src/fraction.rs
> +    /// The fraction corresponding to 0/0.
I think we can just use `Fraction::default` for this?

2022-03-13 01:07 UTC, michaelhly requested changes
Let's try to preserve backwards compatibility in the `stable-swap-math` create when possible.

2022-03-13 01:07 UTC, michaelhly commented on stable-swap-math/src/curve.rs
>      pub fn compute_mint_amount_for_deposit(
Same here for backwards compatibility. 

```rs
compute_mint_amount_for_deposit_with_exchange_rates {
    ....
}
```

2022-03-13 01:07 UTC, michaelhly commented on stable-swap-math/src/curve.rs
>      pub fn compute_withdraw_one(
Same as above for backwards compatibility, if possible.

2022-03-13 01:07 UTC, michaelhly commented on stable-swap-math/src/curve.rs
> +        swap_destination_exchange_rate: Fraction,
Backwards compatibility if possible.

2022-03-13 01:08 UTC, michaelhly commented
Also it might be a good idea to change the Default trait for `Fraction` to be `ONE`?

2022-03-13 03:21 UTC, 0xIsshiki commented
I'm actually not sure the default value of `Fraction` should be 1/1. Maybe if the struct were called `ExchangeRate`, then 1/1 would be the first default that people think of. But I think if you were to ask a random programmer on the street what they thought the default value of a `Fraction` should be, a lot would probably say 0/0.

What do you think?

2022-03-13 03:28 UTC, michaelhly commented on stable-swap-client/src/state.rs
> +        if exchange_rate_override.numerator == 0 && exchange_rate_override.denominator == 0 {
Can we implement a method on `Fraction` to check if the denominator is `0`?

2022-03-13 03:44 UTC, michaelhly commented on stable-swap-client/src/state.rs
> +        }
```suggestion
        Fraction::UNDEFINED
```

2022-03-13 04:04 UTC, michaelhly approved these changes

2022-03-13 04:04 UTC, michaelhly commented on stable-swap-client/src/instruction.rs
> +    token_b_exchange_rate_override: Fraction,
Let's follow up and revert the override setters in `init`. Instead, let us will set these by combining the init instruction with the setter instruction(s) client-side.

2022-03-13 07:09 UTC, merged